default-steps: &default-steps
  - checkout

  - run:
      name: "Init submodules"
      command: git submodule update --init

  - cache-restore:
      name: "Restore dependencies cache"
      key: &deps-cache-key deps-0-{{ .Environment.CXX }}{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}

  - run:
      name: "Configure"
      command: |
        mkdir -p build && cd build
        cmake .. -G "${GENERATOR}" -DCOVERAGE=ON

  - run:
      name: "Upload Hunter cache"
      command: |
        if [ ! "$CIRCLE_PR_NUMBER" ]; then  # Skip forked PRs.
          cmake --build build --target hunter_upload_cache
        fi

  - run:
      name: "Build"
      command: cmake --build build -- -j8

  - cache-save:
      name: "Save dependencies cache"
      key: *deps-cache-key
      paths:
        - ~/cpp-ethereum/build/deps

  - store_artifacts:
      path: build/eth/eth
      destination: eth

  - cache-restore:
      name: "Restore Ethash DAG file"
      key: ethash-dag0

  - run:
      name: "Test"
      pwd: ~/cpp-ethereum/build
      command: |
        export ETHEREUM_TEST_PATH=~/cpp-ethereum/test/jsontests
        export TMPDIR=/dev/shm
        test/testeth -t BlockchainTests &
        test/testeth -t StateTestsGeneral &
        test/testeth -t 'KeyStore:Crypto:KeyManagerTests' &
        test/testeth -t '!BlockchainTests:!StateTestsGeneral:!KeyStore:!Crypto:!KeyManagerTests' &
        wait

  - cache-save:
      name: "Save Ethash DAG file"
      key: ethash-dag0
      paths:
        - ~/.ethash/full-R23-0000000000000000

  - run:
      name: "Code coverage"
      pwd: ~/cpp-ethereum/build
      command: |
        bash <(curl -s https://codecov.io/bash) -X fix

version: 2
jobs:

  default-clang5-ninja:
    environment:
      - CXX: clang++-5.0
      - CC:  clang-5.0
      - GENERATOR: Ninja
    docker:
      - image: ethereum/cpp-build-env
    working_directory: ~/cpp-ethereum
    steps: *default-steps

  debug-gcc4-ninja:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++-4.8
      - CC:  gcc-4.8
      - GENERATOR: Ninja
    docker:
      - image: ethereum/cpp-build-env
    working_directory: ~/cpp-ethereum
    steps: *default-steps

workflows:
  version: 2
  cpp-ethereum:
    jobs:
      - default-clang5-ninja
      - debug-gcc4-ninja